# Generated by Django 3.1 on 2023-03-08 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.CharField(max_length=255, verbose_name='Genre')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=255, verbose_name='Movie name')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('producer', models.CharField(max_length=255, verbose_name='Producer')),
                ('cover', models.CharField(max_length=500, verbose_name='Link to cover')),
                ('poster', models.CharField(max_length=500, verbose_name='Link to poster')),
                ('isTop', models.BooleanField(default=True, verbose_name='Is top')),
                ('isRecommended', models.BooleanField(default=False, verbose_name='Is recommended')),
                ('description', models.TextField(verbose_name='Description')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('movieLink', models.CharField(max_length=500, verbose_name='Link to movie (from youtube)')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HTApp.genre', verbose_name='Genre')),
            ],
        ),
    ]
