# Generated by Django 3.1 on 2023-03-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HTApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='isRecommended',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is recommended'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='isTop',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is top'),
        ),
    ]
